BLocal.Web.Manager.MVC3/Models/Home/ImportExportData.cs
using System;
using System.Collections.Generic;
using BLocal.Core;
using BLocal.Web.Manager.Business;

namespace BLocal.Web.Manager.Models.Home
{
    public class ImportExportData
    {
        public readonly IEnumerable<PartNode> PartNodes;
        public readonly Locale[] Locales;
        public readonly String ProviderConfigName;

        public ImportExportData(IEnumerable<PartNode> partNodes, Locale[] locales, String providerConfigName)
        {
            PartNodes = partNodes;
            Locales = locales;
            ProviderConfigName = providerConfigName;
        }
    }
}

BLocal.Web.Manager.MVC3/Models/Home/QualifiedLocalization.cs
using System;
using BLocal.Core;

namespace BLocal.Web.Manager.Models.Home
{
    public class QualifiedLocalization
    {
        public Qualifier.Unique Qualifier { get; set; }
        public String Value { get; set; }
        public DateTime LastAcces { get; set; }

        public QualifiedLocalization(Qualifier.Unique qualifier, String value, DateTime lastAccess)
        {
            Qualifier = qualifier;
            Value = value;
            LastAcces = lastAccess;
        }
    }
}

BLocal.Web.Manager.MVC3/Models/Home/SynchronizationItem.cs
using System;

namespace BLocal.Web.Manager.Models.Home
{
    public class SynchronizationItem
    {
        public String Side { get; set; }
        public String Part { get; set; }
        public String Locale  { get; set; }
        public String Key { get; set; }
    }
}

BLocal.Web.Manager.MVC3/Controllers/HistoryController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using BLocal.Core;
using BLocal.Web.Manager.Business;
using BLocal.Web.Manager.Context;
using BLocal.Web.Manager.Extensions;
using BLocal.Web.Manager.Models.History;
using BLocal.Web.Manager.Providers.RemoteAccess;

namespace BLocal.Web.Manager.Controllers
{
    [Authenticate]
    public class HistoryController : Controller
    {
        public ProviderGroupFactory ProviderGroupFactory { get; set; }

        public HistoryController()
        {
            ProviderGroupFactory = new ProviderGroupFactory();
        }

        public ActionResult Index(String providerConfigName)
        {
            var localization = ProviderGroupFactory.CreateProviderGroup(providerConfigName);

            var allValues = localization.ValueManager.GetAllValuesQualified();

            var history = localization.HistoryManager.ProvideHistory()
                .OrderByDescending(h => h.LatestEntry().DateTimeUtc)
                .ToList();

            var historyChecker = new HistoryChecker();
            if(historyChecker.FindValuesConflictingWithHistory(allValues, history).Any())
                return RedirectToAction("Broken", new { providerConfigName = providerConfigName });

            var model = new HistoryData {
                Provider = localization,
                History = history
            };
            return View(model);
        }

        public ActionResult Fix(String providerConfigName)
        {
            var localization = ProviderGroupFactory.CreateProviderGroup(providerConfigName);
            var allValues = localization.ValueManager.GetAllValuesQualified().ToArray();
            var history = localization.HistoryManager.ProvideHistory();
            var historyChecker = new HistoryChecker();
            var historyConflicts = historyChecker.FindValuesConflictingWithHistory(allValues, history).ToArray();

            if(historyConflicts.Length > 3 && localization.HistoryManager is RemoteAccessManager)
                ((RemoteAccessManager) localization.HistoryManager).StartBatch();

            foreach(var conflict in historyConflicts)
                localization.HistoryManager.ProgressHistory(new QualifiedValue(conflict.Qualifier, conflict.CurrentValue), Session.Get<String>("author"));

            localization.HistoryManager.Persist();
            
            if(historyConflicts.Length > 3 && localization.HistoryManager is RemoteAccessManager)
                ((RemoteAccessManager) localization.HistoryManager).EndBatch();

            return RedirectToAction("Index", new { providerConfigName });
        }

        public ActionResult Broken(String providerConfigName)
        {
            var provider = ProviderGroupFactory.CreateProviderGroup(providerConfigName);
            var allValues = provider.ValueManager.GetAllValuesQualified().ToArray();
            var history = provider.HistoryManager.ProvideHistory();
            var historyChecker = new HistoryChecker();
            var historyConflicts = historyChecker.FindValuesConflictingWithHistory(allValues, history).ToList();
            return View(new BrokenHistoryData { ConflictingValues = historyConflicts, Provider = provider });
        }
    }
}

BLocal.Web.Manager.MVC3/Controllers/ImportExportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using BLocal.Core;
using BLocal.Web.Manager.Business;
using BLocal.Web.Manager.Context;
using BLocal.Web.Manager.Extensions;
using BLocal.Web.Manager.Models.ImportExport;
using BLocal.Web.Manager.Models.TranslationVerification;
using CsvHelper;

namespace BLocal.Web.Manager.Controllers
{
    [Authenticate]
    public class ImportExportController : Controller
    {
        public ProviderGroupFactory ProviderGroupFactory { get; set; }

        public ImportExportController()
        {
            ProviderGroupFactory = new ProviderGroupFactory();
        }

        public ActionResult Index(String providerConfigName)
        {
            var providerGroup = ProviderGroupFactory.CreateProviderGroup(providerConfigName);
            var allValues = providerGroup.ValueManager.GetAllValuesQualified().ToArray();
            var allParts = allValues.Select(value => value.Qualifier.Part).Distinct().OrderBy(p => p.ToString()).ToArray();
            var allLocales = allValues.Select(value => value.Qualifier.Locale).Distinct().OrderBy(l => l.ToString()).ToArray();

            var history = providerGroup.HistoryManager.ProvideHistory();
            var historyChecker = new HistoryChecker();
            historyChecker.ValidateHistory(allValues, history, Session.Get<String>("author"));

            var partNodes = new Dictionary<Part, PartNode>();
            foreach (var part in allParts)
            {
                var isRoot = part.Parent == null;
                var node = new PartNode(part, isRoot);

                partNodes.Add(part, node);
                if (!isRoot)
                {
                    var fixNode = node;
                    while (fixNode.Part.Parent != null)
                    {
                        var parentNode = new PartNode(fixNode.Part.Parent, fixNode.Part.Parent.Parent == null);
                        if (partNodes.ContainsKey(parentNode.Part))
                        {
                            partNodes[parentNode.Part].SubParts.Add(fixNode);
                            break;
                        }

                        partNodes.Add(parentNode.Part, parentNode);
                        parentNode.SubParts.Add(fixNode);
                        fixNode = parentNode;
                    }
                }
            }
            foreach (var part in allParts.Where(part => part.Parent != null))
                partNodes.Remove(part);

            return View(new ImportExportData(partNodes.Values, allLocales, providerGroup));
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Export(String providerConfigName, String[] parts, String format, String locale, bool omitLocaleBlanks)
        {
            var providerGroup = ProviderGroupFactory.CreateProviderGroup(providerConfigName);
            var allValues = providerGroup.ValueManager.GetAllValuesQualified().ToArray();
            var selectedLocale = new Locale(locale);
            var groupedTranslations = allValues
                .Where(v => parts.Contains(v.Qualifier.Part.ToString()))
                .ToLookup(v => new Qualifier(v.Qualifier.Part, TranslationVerificationData.NoLocale, v.Qualifier.Key));

            var records = groupedTranslations
                .Select(group =>
                    group
                        .SingleOrDefault(v => Equals(v.Qualifier.Locale.ToString(), locale))
                        ?? (omitLocaleBlanks ? null : new QualifiedValue(
                            new Qualifier.Unique(group.Key.Part, selectedLocale, group.Key.Key),
                            String.Empty
                        ))
                )
                .Where(v => v != null)
                .Select(v => new ImportExportRecord(v.Qualifier.Part.ToString(), v.Qualifier.Key, v.Value))
                .ToArray();

            var stream = new MemoryStream();
            try
            {
                switch (format.ToLowerInvariant())
                {
                    case "csv":
                        var streamWriter = new StreamWriter(stream);
                        var csvWriter = new CsvWriter(streamWriter);
                        csvWriter.Configuration.Delimiter = ";";

                        csvWriter.WriteRecords(records);
                        streamWriter.Flush();
                        stream.Seek(0, SeekOrigin.Begin);

                        return File(stream, "text/csv", providerConfigName + " - " + selectedLocale + " - " + DateTime.Now.ToString("yyyy-MM-dd HHmmss") + ".csv");
                    case "xml":
                        var xmlRecords = new XElement("Localizations",
                            records.Select(r => new XElement("Localization",
                                new XElement("Part", r.Part),
                                new XElement("Key", r.Key),
                                new XElement("Value", r.Value),
                                new XElement("DeleteOnImport", r.DeleteOnImport)
                            ))
                        );

                        xmlRecords.Save(stream);
                        stream.Seek(0, SeekOrigin.Begin);

                        return File(stream, "text/xml", providerConfigName + " - " + selectedLocale + " - " + DateTime.Now.ToString("yyyy-MM-dd HHmmss") + ".xml");
                }
            }
            catch
            {
                stream.Dispose();
                return null;
            }
            throw new Exception("Unknown data format: " + format);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Import(String providerConfigName, String locale, HttpPostedFileBase postedFile)
        {
            var providerGroup = ProviderGroupFactory.CreateProviderGroup(providerConfigName);
            var allValues = providerGroup.ValueManager.GetAllValuesQualified().ToArray();
            var selectedLocale = new Locale(locale);
            var valuesByPartKey = allValues
                .Where(value => value.Qualifier.Locale.Equals(selectedLocale))
                .ToDictionary(v => new Qualifier.Unique(v.Qualifier.Part, selectedLocale, v.Qualifier.Key));

            var extention = postedFile.FileName.Split('.').Last();
            var records = new List<ImportExportRecord>();
            
            //var content = new StringReader(@"put your csv content here");
            var content = new StreamReader(postedFile.InputStream);

            switch (extention)
            {
                case "csv":
                    using (var reader = new CsvReader(content))
                    {
                        reader.Configuration.Delimiter = ";";
                        records.AddRange(reader.GetRecords<ImportExportRecord>());
                    }
                    break;
                case "xml":
                    // ReSharper disable PossibleNullReferenceException
                    var document = XDocument.Load(postedFile.InputStream);
                    records.AddRange(document.Root.Descendants("Localization").Select(
                        xel => new ImportExportRecord(xel.Element("Part").Value, xel.Element("Key").Value, xel.Element("Value").Value) { DeleteOnImport = xel.Element("DeleteOnImport").Value.Trim().ToLowerInvariant() != "false" }
                    ));
                    // ReSharper restore PossibleNullReferenceException
                    break;
            }

            var inserts = new List<QualifiedValue>();
            var updates = new List<Tuple<QualifiedValue, ImportExportRecord>>();
            var deletes = new List<QualifiedValue>();

            foreach (var record in records)
            {
                QualifiedValue correspondingValue;
                var recordQualfier = new Qualifier.Unique(Part.Parse(record.Part), selectedLocale, record.Key);

                if (valuesByPartKey.TryGetValue(recordQualfier, out correspondingValue))
                {
                    if (record.DeleteOnImport)
                        deletes.Add(correspondingValue);
                    else if (!record.Value.Equals(correspondingValue.Value))
                        updates.Add(Tuple.Create(correspondingValue, record));
                }
                else if (!record.DeleteOnImport)
                    inserts.Add(new QualifiedValue(recordQualfier, record.Value));
            }

            return View(new ImportReportData(providerConfigName, postedFile.FileName, selectedLocale, inserts, updates, deletes));
        }

        [ValidateInput(false)]
        public JsonResult FinalizeUpdate(ImportConfiguration configuration)
        {
            var providerGroup = ProviderGroupFactory.CreateProviderGroup(configuration.ProviderConfigName);
            var selectedLocale = new Locale(configuration.Locale);
            foreach (var update in configuration.Data)
            {
                var qualifiedValue = new QualifiedValue(new Qualifier.Unique(Part.Parse(update.Part), selectedLocale, update.Key), update.Value ?? String.Empty);
                providerGroup.ValueManager.UpdateCreateValue(qualifiedValue);
                providerGroup.HistoryManager.ProgressHistory(qualifiedValue, Session.Get<String>("author"));
            }
            providerGroup.ValueManager.Persist();
            if(providerGroup.ValueManager != providerGroup.HistoryManager)
                providerGroup.HistoryManager.Persist();
            return Json(new { ok = true });
        }

        [ValidateInput(false)]
        public JsonResult FinalizeInsert(ImportConfiguration configuration)
        {
            var providerGroup = ProviderGroupFactory.CreateProviderGroup(configuration.ProviderConfigName);
            var selectedLocale = new Locale(configuration.Locale);
            foreach (var insert in configuration.Data)
            {

BLocal.Web.Manager.MVC3/Controllers/TranslationVerificationController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using BLocal.Core;
using BLocal.Web.Manager.Business;
using BLocal.Web.Manager.Context;
using BLocal.Web.Manager.Extensions;
using BLocal.Web.Manager.Models.TranslationVerification;

namespace BLocal.Web.Manager.Controllers
{
    [Authenticate]
    public class TranslationVerificationController : Controller
    {
        public ProviderGroupFactory ProviderGroupFactory { get; set; }

        public TranslationVerificationController()
        {
            ProviderGroupFactory = new ProviderGroupFactory();
        }

        public ActionResult Index(String providerConfigName)
        {
            var localization = ProviderGroupFactory.CreateProviderGroup(providerConfigName);

            var allValues = localization.ValueManager.GetAllValuesQualified().ToArray();

            var groupedTranslations = allValues
                .ToLookup(v => new Qualifier(v.Qualifier.Part, TranslationVerificationData.NoLocale, v.Qualifier.Key));

            var allLocales = allValues
                .Select(v => v.Qualifier.Locale)
                .Distinct()
                .ToArray();

            return View(new TranslationVerificationData(groupedTranslations, allLocales, localization));
        }

        [ValidateInput(false)]
        public JsonResult Update(String part, String locale, String key, String value, String providerConfigName)
        {
            var providerGroup = ProviderGroupFactory.CreateProviderGroup(providerConfigName);

            var qualifier = new Qualifier.Unique(Part.Parse(part), new Locale(locale), key);
            var qualifiedValue = new QualifiedValue(qualifier, value);
            providerGroup.ValueManager.UpdateCreateValue(qualifiedValue);
            providerGroup.HistoryManager.ProgressHistory(qualifiedValue, Session.Get<String>("author"));

            providerGroup.ValueManager.Persist();
            if (providerGroup.ValueManager != providerGroup.HistoryManager)
                providerGroup.HistoryManager.Persist();

            return Json(new { ok = true });
        }

        [ValidateInput(false)]
        public JsonResult Delete(String part, String key, String providerConfigName)
        {
            var providerGroup = ProviderGroupFactory.CreateProviderGroup(providerConfigName);

            var localizationsToDelete = providerGroup.ValueManager.GetAllValuesQualified().Where(v => v.Qualifier.Part.ToString() == part).ToArray();

            foreach (var localization in localizationsToDelete)
            {
                providerGroup.ValueManager.DeleteValue(localization.Qualifier);
                providerGroup.HistoryManager.ProgressHistory(new QualifiedValue(localization.Qualifier, null), Session.Get<String>("author"));
            }

            providerGroup.ValueManager.Persist();
            if (providerGroup.ValueManager != providerGroup.HistoryManager)
                providerGroup.HistoryManager.Persist();

            return Json(new { ok = true });
        }
    }
}

BLocal.Web.Manager.MVC3/Views/Home/EditLocalization.cshtml
@using BLocal.Web.Manager.Business
@using BLocal.Web.Manager.Extensions
@model IEnumerable<LocalizedPart>
@{
    ViewBag.Title = "Manual Editing";
}
@section Head {
    <script type="text/javascript">
        this.pages = this.pages || {};
        
        $(document).ready(function () {
            pages.current = '@Url.Action("ReloadLocalization")';
            pages.createKey = '@Url.Action("Create", "Home")';
            pages.removeKey = '@Url.Action("Remove", "Home")';
        });
    </script>
}

<h1>@Html.ActionLink("Home", "Overview") - Manual Editing of <span class="accent">@(Session.Get<ProviderGroup>("manualProviderGroup").Name)</span></h1>
<p><span class="open">open</span> | <span class="collapse">collapse</span> | <span class="reload">reload</span> | <span class="hardreload" title="dump localization cache, reload from scratch">hard reload</span></p>
    
<section class="general">
    <h2>Filter</h2>
    <form id="filterform">
        <div><label for="key">Key</label> <input type="text" class="filter" id="key" /></div>
        <div><label for="locale">Locale</label> <input type="text" class="filter" id="locale" /></div>
        <div><label for="content">Content</label> <input type="text" class="filter" id="content" /></div>
        <div><input type="submit" value="Apply Filter" /></div>
    </form>
    <div><p class="result"></p></div>
</section>

@foreach(var localizedPart in Model) {
    @RenderPart(localizedPart)
}

@helper RenderPart(LocalizedPart part) {
    <section class="part">
        <h2><span class="title">@part.Part.ToString()</span> [@part.Localizations.Count]</h2>
        <section class="values">
            @foreach (var value in part.Localizations.OrderBy(value => value.Qualifier.Key).ThenBy(value => value.Qualifier.Locale.Name)) {
                <p>
                    <span class="key">@value.Qualifier.Key</span>
                    <span class="locale"><nobr>@value.Qualifier.Locale</nobr></span>
                    <span class="content" title="@value.Value.Replace(@"""", @"'")">@value.Value</span>
                    <span class="clear"></span>
                </p>
            }
        </section>
        @foreach(var subpart in part.Subparts) {
            @RenderPart(subpart)
        }
    </section>
}
    
<div id="details" class="popup">
    <h2>Details</h2>
    <form>
        <p><span class="lbl part">Part</span><span class="lbl key">Key</span><span class="lbl locale">Locale</span></p>
        <p><input type="text" class="val part"></input><input type="text" class="val key"></input><input type="text" class="val locale"></input></p>
        <p><span class="lbl">Content</span></p>
        <div><textarea class="content"></textarea></div>
        <div>
            <input type="button" class="updaterecreate" value="Save to Original" title="deletes current value, recreates to new value" />
            <input type="button" class="updatecopy" value="Save to Copy" title="creates a copy if key or part changed, does not delete original" />
            <input class="updatedelete" type="button" value="Clean Delete" title="bye-bye" />
            <p>(visible changes are indications, press reload to confirm)</p>
        </div>
    </form>
</div>

BLocal.Web.Manager.MVC3/Views/Home/Index.cshtml
@using System.Configuration
@{
    ViewBag.Title = "Authentication";
}
<meta name="google-signin-client_id" content="@ConfigurationManager.AppSettings["GoogleOAuthCliendId"]">
<script src="https://apis.google.com/js/platform.js" async defer></script>
<script type="text/javascript">
    function onSignIn(googleUser) {
        // Send ID-Token to controller
        $.ajax({
            url: '@Url.Action("GoogleLogin", "Home")',
            type: 'POST',
            dataType: 'json',
            cache: false,
            data: { token: googleUser.getAuthResponse().id_token },
            success: function (data) {
                if (data === "ok") {
                    location.href = "/Home/Overview";
                } else if (data === "bad_domain") {
                    alert("Your account is not allowed to use this service. You will be logged out. Please try to log in using account allowed to enter.");
                    gapi.auth2.getAuthInstance().disconnect();
                } else if (data === "disabled") {
                    alert("Google log in is disabled now. Try to log in using username and password.");
                }
            }
        });
    }
</script>

<h1>Authentication</h1>
    
@if (String.IsNullOrWhiteSpace(ConfigurationManager.AppSettings["password"])) {
    <p>Please edit the web.config in the root directory to configure your provider(s). Once you've changed the password value there, you will be able to authenticate.</p>
}
else {
    <section class="general">
        @if (ConfigurationManager.AppSettings["StandardLogInEnabled"] == "true")
        {
            <h2>Please provide first name and password</h2>
            using (Html.BeginForm("Authenticate", "Home", FormMethod.Post))
             {
                 <input type="text" name="username" value="" placeholder="first name"/>
                 <input type="password" name="password" placeholder="password"/>
                 <input type="submit" value="Authenticate"/>
             }
        }
        @if (ConfigurationManager.AppSettings["GoogleLogInEnabled"] == "true")
        {
            <h2>Authenticate using google account</h2>
            <div class="g-signin2" data-onsuccess="onSignIn"></div>
        }
        @if (ConfigurationManager.AppSettings["GoogleLogInEnabled"] == "false" &&
                     ConfigurationManager.AppSettings["StandardLogInEnabled"] == "false")
        {
            <h2>All authentication ways are currently disabled. Please contact administrator.</h2>
        }
    </section>
}

BLocal.Web.Manager.MVC3/Views/Home/Overview.cshtml
@using BLocal.Core
@using System.Configuration
@using BLocal.Web.Manager.Configuration
@using BLocal.Web.Manager.Controllers
@using BLocal.Web.Manager.Models.AutomaticSynchronization
@{
    ViewBag.Title = "Localization Manager";
}
@section Head {
    <meta name="google-signin-client_id" content="@ConfigurationManager.AppSettings["GoogleOAuthCliendId"]">
    <script type="text/javascript">
    </script>
}

<h1>Localization Manager - <span class="accent">@Session["Author"]</span></h1>

@if (ConfigurationManager.AppSettings["GoogleLogInEnabled"] == "true")
{
    <script type="text/javascript">
        function googleLogOut() {
            gapi.auth2.getAuthInstance().disconnect();
            $.ajax({
                url: '@Url.Action("EndSession", "Home")',
                type: 'POST',
                dataType: 'text',
                cache: false,
                success: function (data) { location.href = "/Home/index"; }
            });
        };
        function onLoad() {
            gapi.load('auth2', function () {
                gapi.auth2.init();
            });
        }
    </script>
    <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>
    <button onclick="googleLogOut()">Log out</button>  
}

<section class="general">
    <h2>Manual editing</h2>
    @using (Html.BeginForm("Index", "DirectEditing", FormMethod.Get))
    {
        <p>
            <select name="providerConfigName">
                @foreach (var config in ProviderConfig.ProviderGroups)
                {
                    <option>@config.Name</option>
                }
            </select>
            <button type="submit">Edit</button>
        </p>
    }
</section>

<section class="general">
    <h2>View history</h2>
    @using (Html.BeginForm("Index", "History", FormMethod.Get))
    {
        <p>
            <select name="providerConfigName">
                @foreach (var config in ProviderConfig.ProviderGroups)
                {
                    <option>@config.Name</option>
                }
            </select>
            <button type="submit">View</button>
        </p>
    }
</section>
    
<section class="general left">
    <h2>Manual Synchronization</h2>
    @using (Html.BeginForm("Index", "ManualSynchronization", FormMethod.Get))
    {
        <p>
            between
            <select name="leftConfigName">
                @foreach (var config in ProviderConfig.ProviderGroups)
                {
                    <option>@config.Name</option>
                }
            </select>
            and
            <select name="rightConfigName">
                @foreach (var config in ProviderConfig.ProviderGroups)
                {
                    <option>@config.Name</option>
                }
            </select>
            <button type="submit">Start</button>
        </p>
    }
</section>
<section class="general">
    <h2>Import / Export</h2>
    @using (Html.BeginForm("Index", "ImportExport", FormMethod.Get))
    {
        <select name="providerConfigName">
            @foreach (var config in ProviderConfig.ProviderGroups)
            {
                <option>@config.Name</option>
            }
        </select>
        <button type="submit">Start</button>
    }
</section>
<section class="general">
    <h2>Verify translations across locales</h2>
    @using (Html.BeginForm("Index", "TranslationVerification", FormMethod.Get))
    {
        <select name="providerConfigName">
            @foreach (var config in ProviderConfig.ProviderGroups)
            {
                <option>@config.Name</option>
            }
        </select>
        <button type="submit">Start</button>
    }
</section>
<section class="general left">
    <h2>Automatic Synchronization</h2>
    @using (Html.BeginForm("Index", "AutomaticSynchronization", FormMethod.Get, new { target="_blank" }))
    {
        <p>
            between
            <select name="LeftProviderGroupName">
                @foreach (var config in ProviderConfig.ProviderGroups)
                {
                    <option>@config.Name</option>
                }
            </select>
            and
            <select name="RightProviderGroupName">
                @foreach (var config in ProviderConfig.ProviderGroups)
                {
                    <option>@config.Name</option>
                }
            </select>
        </p>
        <p>
            When a value is added on the right, resolve using
            <select name="LeftMissingStrategy">
                @foreach (var missingStrategyName in Enum.GetNames(typeof(SynchronizationSettings.MissingResolutionStrategy)))
                {
                    <option>@missingStrategyName</option>
                }
            </select>
        </p>
        <p>
            When a value is added on the left, resolve using
            <select name="RightMissingStrategy">
                @foreach (var missingStrategyName in Enum.GetNames(typeof(SynchronizationSettings.MissingResolutionStrategy)))
                {
                    <option>@missingStrategyName</option>
                }
            </select>
        </p>
        <p>
            When the two environments have different values, resolve using
            <select name="DifferingStrategy">
                @foreach (var differingStrategyName in Enum.GetNames(typeof(SynchronizationSettings.DifferingResolutionStrategy)))
                {
                    <option>@differingStrategyName</option>
                }
            </select>
        </p>
        <p>
            <select name="Execute">
                <option value="false">Just show output</option>
                <option value="true">Execute for real</option>
            </select>
            <button type="submit">Start</button>
        </p>
    }
</section>
<section class="general left">
    Localization Manager Version: @System.Reflection.Assembly.GetAssembly(typeof(HomeController)).GetName().Version
</section>