BLocal.Web.Manager.MVC3/Models/ManualSynchronization/SynchronizationData.cs
using BLocal.Core;
using BLocal.Web.Manager.Business;

namespace BLocal.Web.Manager.Models.ManualSynchronization
{
    public class SynchronizationData
    {
        public readonly ProviderGroup Left;
        public readonly ProviderGroup Right;
        public readonly QualifiedHistoricalValue[] LeftValuesNotRight;
        public readonly QualifiedHistoricalValue[] RightValuesNotLeft;
        public readonly QualifiedHistoricalValuePair[] ValueDifferences;

        public SynchronizationData(ProviderGroup left, ProviderGroup right, QualifiedHistoricalValue[] leftValuesNotRight, QualifiedHistoricalValue[] rightValuesNotLeft, QualifiedHistoricalValuePair[] valueDifferences)
        {
            Left = left;
            Right = right;
            LeftValuesNotRight = leftValuesNotRight;
            RightValuesNotLeft = rightValuesNotLeft;
            ValueDifferences = valueDifferences;
        }

        public class QualifiedHistoricalValue
        {
            public QualifiedHistoricalValue(QualifiedValue value, QualifiedHistory history)
            {
                Value = value;
                History = history;
            }

            public QualifiedValue Value { get; set; }
            public QualifiedHistory History { get; set; }
        }

        public class QualifiedHistoricalValuePair
        {
            public readonly QualifiedHistoricalValue Left;
            public readonly QualifiedHistoricalValue Right;

            public QualifiedHistoricalValuePair(QualifiedHistoricalValue left, QualifiedHistoricalValue right)
            {
                Left = left;
                Right = right;
            }
        }
    }
}

BLocal.Web.Manager.MVC3/Models/ManualSynchronization/SynchronizationItem.cs
using System;

namespace BLocal.Web.Manager.Models.ManualSynchronization
{
    public class SynchronizationItem
    {
        public Side Side { get; set; }
        public String Part { get; set; }
        public String Locale  { get; set; }
        public String Key { get; set; }
    }

    public enum Side
    {
        Right,
        Left
    }
}

BLocal.Web.Manager.MVC3/Controllers/ManualSynchronizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BLocal.Core;
using BLocal.Web.Manager.Business;
using BLocal.Web.Manager.Context;
using BLocal.Web.Manager.Models.ManualSynchronization;
using BLocal.Web.Manager.Providers.RemoteAccess;

namespace BLocal.Web.Manager.Controllers
{
    [Authenticate]
    public class ManualSynchronizationController : Controller
    {
        public ProviderGroupFactory ProviderGroupFactory { get; set; }

        public ManualSynchronizationController()
        {
            ProviderGroupFactory = new ProviderGroupFactory();
        }

        private static QualifiedHistory MergeHistory(Qualifier.Unique qualifier, ProviderGroup group1, ProviderGroup group2)
        {
            var group1History = group1.HistoryManager.GetHistory(qualifier);
            var group2History = group2.HistoryManager.GetHistory(qualifier);
            return HistoryMerger.MergeHistoryEntries(group1History, group2History);
        }

        public ActionResult Index(String leftConfigName, String rightConfigName, Boolean hardReload = false)
        {
            var leftProviders = ProviderGroupFactory.CreateProviderGroup(leftConfigName);
            leftProviders.ValueManager.Reload();
            var leftValues = leftProviders.ValueManager.GetAllValuesQualified().ToArray();
            
            var rightProviders = ProviderGroupFactory.CreateProviderGroup(rightConfigName);
            rightProviders.ValueManager.Reload();
            var rightValues = rightProviders.ValueManager.GetAllValuesQualified().ToArray();

            var historyChecker = new HistoryChecker();
            historyChecker.ValidateHistory(leftValues, leftProviders.HistoryManager.ProvideHistory(), leftConfigName);
            historyChecker.ValidateHistory(rightValues, rightProviders.HistoryManager.ProvideHistory(), rightConfigName);

            var leftNotRight = leftValues.Where(lv => !rightValues.Select(rv => rv.Qualifier).Contains(lv.Qualifier))
                .Select(lv => new SynchronizationData.QualifiedHistoricalValue(lv, MergeHistory(lv.Qualifier, leftProviders, rightProviders)))
                .ToArray();
            var rightNotLeft = rightValues.Where(rv => !leftValues.Select(lv => lv.Qualifier).Contains(rv.Qualifier))
                .Select(rv => new SynchronizationData.QualifiedHistoricalValue(rv, MergeHistory(rv.Qualifier, leftProviders, rightProviders)))
                .ToArray();

            var valueDifferences = leftValues
                .Join(rightValues, v => v.Qualifier, v => v.Qualifier, (lv, rv) => new SynchronizationData.QualifiedHistoricalValuePair(
                    new SynchronizationData.QualifiedHistoricalValue(lv, leftProviders.HistoryManager.GetHistory(lv.Qualifier)),
                    new SynchronizationData.QualifiedHistoricalValue(rv, rightProviders.HistoryManager.GetHistory(rv.Qualifier))
                ))
                .Where(dv => !Equals(dv.Left.Value, dv.Right.Value))
                .ToArray();

            return View(new SynchronizationData(leftProviders, rightProviders, leftNotRight, rightNotLeft, valueDifferences));
        }

        [ValidateInput(false)]
        public JsonResult Remove(SynchronizationItem[] items, String leftProviderConfigName, String rightProviderConfigName)
        {
            var changedLocalizationSides = new HashSet<ProviderGroup>();
            var sourcedLocalizationSides = new HashSet<ProviderGroup>();
            var sideProviders = new Dictionary<Side, ProviderGroup> {
                { Side.Left, ProviderGroupFactory.CreateProviderGroup(leftProviderConfigName) },
                { Side.Right, ProviderGroupFactory.CreateProviderGroup(rightProviderConfigName) }
            };

            if (items.Length >= 3)
                foreach(var manager in sideProviders.Select(p => p.Value.ValueManager).OfType<RemoteAccessManager>())
                    manager.StartBatch();

            foreach (var item in items)
            {
                var localizationFrom = sideProviders[item.Side];
                var localizationTo = sideProviders[item.Side == Side.Left ? Side.Right : Side.Left];

                if (!changedLocalizationSides.Contains(localizationTo))
                    changedLocalizationSides.Add(localizationTo);
                if (!sourcedLocalizationSides.Contains(localizationFrom))
                    sourcedLocalizationSides.Add(localizationFrom);

                var qualifier = new Qualifier.Unique(Part.Parse(item.Part), new Locale(item.Locale), item.Key);
                EnsureHistoryLoaded(localizationFrom, qualifier);
                localizationTo.ValueManager.DeleteValue(qualifier);
                HistoryMerger.MergeHistory(qualifier, localizationFrom.HistoryManager, localizationTo.HistoryManager);
            }

            // persist any changes
            foreach (var localization in changedLocalizationSides)
            {
                localization.ValueManager.Persist();
                if (localization.ValueManager != localization.HistoryManager)
                    localization.HistoryManager.Persist();
            }
            foreach (var localization in sourcedLocalizationSides.Except(changedLocalizationSides))
            {
                localization.HistoryManager.Persist();
            }

            if (items.Length >= 5)
                foreach (var manager in sideProviders.Select(p => p.Value.ValueManager).OfType<RemoteAccessManager>())
                    manager.EndBatch();

            return Json(new { ok = true });
        }

        [ValidateInput(false)]
        public JsonResult Duplicate(SynchronizationItem[] items, String leftProviderConfigName, String rightProviderConfigName)
        {
            var changedLocalizationSides = new HashSet<ProviderGroup>();
            var sourcedLocalizationSides = new HashSet<ProviderGroup>();
            var sideProviders = new Dictionary<Side, ProviderGroup> {
                { Side.Left, ProviderGroupFactory.CreateProviderGroup(leftProviderConfigName) },
                { Side.Right, ProviderGroupFactory.CreateProviderGroup(rightProviderConfigName) }
            };

            if (items.Length >= 3)
                foreach (var manager in sideProviders.Select(p => p.Value.ValueManager).OfType<RemoteAccessManager>())
                    manager.StartBatch();

            foreach (var item in items)
            {
                var localizationFrom = sideProviders[item.Side];
                var localizationTo = sideProviders[item.Side == Side.Left ? Side.Right : Side.Left];

                if (localizationFrom == null || localizationTo == null)
                    throw new Exception("Localization not loaded!");

                if (!changedLocalizationSides.Contains(localizationTo))
                    changedLocalizationSides.Add(localizationTo);
                if (!sourcedLocalizationSides.Contains(localizationFrom))
                    sourcedLocalizationSides.Add(localizationFrom);

                var qualifier = new Qualifier.Unique(Part.Parse(item.Part), new Locale(item.Locale), item.Key);
                EnsureHistoryLoaded(localizationFrom, qualifier);
                localizationTo.ValueManager.UpdateCreateValue(localizationFrom.ValueManager.GetQualifiedValue(qualifier));
                HistoryMerger.MergeHistory(qualifier, localizationFrom.HistoryManager, localizationTo.HistoryManager);
            }

            // persist any changes
            foreach (var localization in changedLocalizationSides)
            {
                localization.ValueManager.Persist();
                if(localization.ValueManager != localization.HistoryManager)
                    localization.HistoryManager.Persist();
            }
            foreach (var localization in sourcedLocalizationSides.Except(changedLocalizationSides))
            {
                localization.HistoryManager.Persist();
            }

            if (items.Length >= 3)
                foreach (var manager in sideProviders.Select(p => p.Value.ValueManager).OfType<RemoteAccessManager>())
                    manager.EndBatch();

            return Json(new { ok = true });
        }

        [ValidateInput(false)]
        public JsonResult Update(SynchronizationItem[] items, String leftProviderConfigName, String rightProviderConfigName)
        {
            var changedLocalizationSides = new HashSet<ProviderGroup>();
            var sourcedLocalizationSides = new HashSet<ProviderGroup>();
            var sideProviders = new Dictionary<Side, ProviderGroup> {
                { Side.Left, ProviderGroupFactory.CreateProviderGroup(leftProviderConfigName) },
                { Side.Right, ProviderGroupFactory.CreateProviderGroup(rightProviderConfigName) }
            };

            if (items.Length >= 3)
                foreach (var manager in sideProviders.Select(p => p.Value.ValueManager).OfType<RemoteAccessManager>())
                    manager.StartBatch();

            foreach (var item in items)
            {
                var localizationFrom = sideProviders[item.Side];
                var localizationTo = sideProviders[item.Side == Side.Left ? Side.Right : Side.Left];

                if (localizationFrom == null || localizationTo == null)
                    throw new Exception("Localization not loaded!");

                if (!changedLocalizationSides.Contains(localizationTo))
                    changedLocalizationSides.Add(localizationTo);
                if (!sourcedLocalizationSides.Contains(localizationFrom))
                    sourcedLocalizationSides.Add(localizationFrom);

                var qualifier = new Qualifier.Unique(Part.Parse(item.Part), new Locale(item.Locale), item.Key);
                EnsureHistoryLoaded(localizationFrom, qualifier);
                localizationTo.ValueManager.UpdateCreateValue(localizationFrom.ValueManager.GetQualifiedValue(qualifier));

BLocal.Web.Manager.MVC3/Views/ManualSynchronization/Index.cshtml
@model BLocal.Web.Manager.Models.ManualSynchronization.SynchronizationData
@{
    ViewBag.Title = "Synchronization";
    ViewBag.PageName = "ManualSynchronization.Index";
}
@section Head {
    <script type="text/javascript">
        window.urls = window.urls || {};
        window.urls.current = '@Html.Raw(Url.Action("Index", "ManualSynchronization", new { leftProviderConfigName = Model.Left.Name, rightProviderConfigName = Model.Right.Name }))';
        window.urls.remove = '@Html.Raw(Url.Action("Remove", "ManualSynchronization", new { leftProviderConfigName = Model.Left.Name, rightProviderConfigName = Model.Right.Name }))';
        window.urls.duplicate = '@Html.Raw(Url.Action("Duplicate", "ManualSynchronization", new { leftProviderConfigName = Model.Left.Name, rightProviderConfigName = Model.Right.Name }))';
        window.urls.update = '@Html.Raw(Url.Action("Update", "ManualSynchronization", new { leftProviderConfigName = Model.Left.Name, rightProviderConfigName = Model.Right.Name }))';
    </script>
}

<h1>
    @Html.ActionLink("Home", "Overview", "Home") -
    Synchronization between <span style="color: @Model.Left.Color">@Model.Left.Name</span>
    and <span style="color: @Model.Right.Color">@Model.Right.Name</span>
    as <span class="accent">@Session["author"]</span>
</h1>
<section class="general">
        <input type="checkbox" id="authorcheck" data-author="@Session["author"]" checked="checked"/>
        <label for="authorcheck">Show only my changes (<span class="accent">@Session["author"]</span>)</label>
</section>
<section class="general" data-from="left">
    <h2>
        Values existing on
        <span style="color: @Model.Left.Color">@Model.Left.Name</span>
        but not on
        <span style="color: @Model.Right.Color">@Model.Right.Name</span>
        (@Model.LeftValuesNotRight.Length)
    </h2>
    <p>
        <button class="select">Select All</button>
        <button class="deselect">Deselect All</button>
        <button class="delete">Delete from <span style="color: @Model.Left.Color">@Model.Left.Name</span></button>
        <button class="duplicate">Create on <span style="color: @Model.Right.Color">@Model.Right.Name</span></button>
    </p>
    <table cellpadding="0" cellspacing="0"><tbody>
        @foreach (var value in Model.LeftValuesNotRight) {
            <tr class="lrvalue" data-author="@value.History.LatestEntry().Author">
                <td style="white-space: nowrap">
                    <input type="checkbox" name="values" data-side="left" data-part="@value.Value.Qualifier.Part" data-locale="@value.Value.Qualifier.Locale" data-key="@value.Value.Qualifier.Key"/>
                </td>
                <td style="white-space: nowrap;">
                    @value.Value.Qualifier.Key <br />
                    <span class="localepart">@value.Value.Qualifier.Locale | @value.Value.Qualifier.Part</span><br />
                    <span class="localepart">@value.History.LatestEntry().DateTimeUtc.ToLocalTime() - @value.History.LatestEntry().Author</span>
                </td>
                <td style="width: 99%;">@value.Value.Value</td>
            </tr>
        }
    </tbody></table>
</section>
<section class="general" data-from="right">
    <h2>
        Values that exist on
        <span style="color: @Model.Right.Color">@Model.Right.Name</span>
        but not on
        <span style="color: @Model.Left.Color">@Model.Left.Name</span>
        (@Model.RightValuesNotLeft.Length)
    </h2>
    <p>
        <button class="select">Select All</button>
        <button class="deselect">Deselect All</button>
        <button class="delete">Delete from <span style="color: @Model.Right.Color">@Model.Right.Name</span></button>
        <button class="duplicate">Create on <span style="color: @Model.Left.Color">@Model.Left.Name</span></button>
    </p>
    <table cellpadding="0" cellspacing="0"><tbody>
        @foreach (var value in Model.RightValuesNotLeft)
        {
            <tr class="lrvalue" data-author="@value.History.LatestEntry().Author">
                <td style="white-space: nowrap">
                    <input type="checkbox" name="values" data-side="right" data-part="@value.Value.Qualifier.Part" data-locale="@value.Value.Qualifier.Locale" data-key="@value.Value.Qualifier.Key"/>
                </td>
                <td style="white-space: nowrap;">
                    @value.Value.Qualifier.Key <br />
                    <span class="localepart">@value.Value.Qualifier.Locale | @value.Value.Qualifier.Part</span><br />
                    <span class="localepart">@value.History.LatestEntry().DateTimeUtc.ToLocalTime() - @value.History.LatestEntry().Author</span>
                </td>
                <td style="width: 99%;">@value.Value.Value</td>
            </tr>
        }
    </tbody></table>
</section>
<section class="general">
    <h2>Values that differ between the two (@Model.ValueDifferences.Length)</h2>
    <p>
        <button class="accept">Execute changes made below</button>
    </p>
    @foreach (var value in Model.ValueDifferences)
    {
        <section class="difference" data-author="@value.Left.History.LatestEntry().Author|@value.Right.History.LatestEntry().Author">
            <h2>@value.Left.Value.Qualifier.Key</h2>
            <p class="localepart">@value.Left.Value.Qualifier.Locale | @value.Left.Value.Qualifier.Part</p>
            <section class="comparison">
                <label class="left">
                    <p class="value">@value.Right.Value.Value</p>
                    <p>
                        <input type="checkbox" data-provider="@Model.Left.Name" data-affected-side="right" data-part="@value.Left.Value.Qualifier.Part" data-locale="@value.Left.Value.Qualifier.Locale" data-key="@value.Left.Value.Qualifier.Key" />
                        Change on <span style="color: @Model.Left.Color">@Model.Left.Name</span> using this value
                        <br />
                        @value.Right.History.LatestEntry().DateTimeUtc.ToLocalTime() - @value.Right.History.LatestEntry().Author
                    </p>
                </label>
                <label class="right">
                    <p class="value">@value.Left.Value.Value</p>
                    <p>
                        <input type="checkbox" data-provider="@Model.Right.Name" data-affected-side="left" data-part="@value.Right.Value.Qualifier.Part" data-locale="@value.Right.Value.Qualifier.Locale" data-key="@value.Right.Value.Qualifier.Key" />
                        Change on <span style="color: @Model.Right.Color">@Model.Right.Name</span> using this value
                        <br />
                        @value.Left.History.LatestEntry().DateTimeUtc.ToLocalTime() - @value.Left.History.LatestEntry().Author
                    </p>
                </label>
                <div class="clear"></div>
            </section>
        </section>
    }
</section>