BLocal.Web.Manager.MVC3/Models/DirectEditing/IndexModel.cs
using System.Collections.Generic;
using BLocal.Web.Manager.Business;

namespace BLocal.Web.Manager.Models.DirectEditing
{
    public class IndexModel
    {
        public IEnumerable<LocalizedPart> Parts { get; set; }
        public ProviderGroup Provider { get; set; }
    }
}

BLocal.Web.Manager.MVC3/Models/DirectEditing/LocalizedPart.cs
using System.Collections.Generic;
using BLocal.Core;

namespace BLocal.Web.Manager.Models.DirectEditing
{
    public class LocalizedPart
    {
        public List<LocalizedPart> Subparts { get; set; }
        public List<QualifiedLocalization> Localizations { get; set; }
        public Part Part { get; set; }

        public LocalizedPart(Part part, List<QualifiedLocalization> localizations)
        {
            Part = part;
            Localizations = localizations;
            Subparts = new List<LocalizedPart>();
        }
    }
}

BLocal.Web.Manager.MVC3/Models/DirectEditing/QualifiedLocalization.cs
using System;
using BLocal.Core;

namespace BLocal.Web.Manager.Models.DirectEditing
{
    public class QualifiedLocalization
    {
        public Qualifier.Unique Qualifier { get; set; }
        public String Value { get; set; }
        public QualifiedHistory History { get; set; }

        public QualifiedLocalization(Qualifier.Unique qualifier, String value, QualifiedHistory history)
        {
            Qualifier = qualifier;
            Value = value;
            History = history;
        }
    }
}

BLocal.Web.Manager.MVC3/Controllers/DirectEditingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BLocal.Core;
using BLocal.Web.Manager.Business;
using BLocal.Web.Manager.Context;
using BLocal.Web.Manager.Extensions;
using BLocal.Web.Manager.Models.DirectEditing;
using iChoosr.Sanitizer;

namespace BLocal.Web.Manager.Controllers
{
    [Authenticate]
    public class DirectEditingController : Controller
    {
        public ProviderGroupFactory ProviderGroupFactory { get; set; }
        private ISanitizer _sanitizer;

        private ISanitizer Sanitizer
        {
            get
            {
                if (_sanitizer == null)
                    _sanitizer = HttpContext.Application["sanitizer"] as ISanitizer;

                return _sanitizer;
            }
        }

        public DirectEditingController()
        {
            ProviderGroupFactory = new ProviderGroupFactory();
        }

        public ActionResult Index(String providerConfigName)
        {
            var localization = ProviderGroupFactory.CreateProviderGroup(providerConfigName);
            var localizations = localization.ValueManager.GetAllValuesQualified().ToList();
            var history = localization.HistoryManager.ProvideHistory().ToDictionary(h => h.Qualifier);

            var historyChecker = new HistoryChecker();
            historyChecker.ValidateHistory(localizations, history.Values, providerConfigName);

            var groupedParts = localizations
                .Select(l => new QualifiedLocalization(l.Qualifier, l.Value, history[l.Qualifier]))
                .GroupBy(ql => ql.Qualifier.Part)
                .ToDictionary(@group => @group.Key, @group => new LocalizedPart(@group.Key, @group.ToList()));
            
            // make sure all branches are in the list
            foreach (var kvp in groupedParts.ToList())
                FixTree(groupedParts, kvp.Key);

            // get new list of all branches
            var nodesWithParents = groupedParts.Where(part => part.Key.Parent != null).ToList();

            //add branches to their parents
            foreach (var kvp in nodesWithParents)
                groupedParts[kvp.Key.Parent].Subparts.Add(kvp.Value);

            // remove branches from the list, keeping only root nodes
            foreach (var kvp in nodesWithParents)
                groupedParts.Remove(kvp.Key);

            var model = new IndexModel {Parts = groupedParts.Values, Provider = localization};
            return View(model);
        }

        [ValidateInput(false)]
        public JsonResult UpdateCreateValue(String part, String locale, String key, String content, String providerConfigName)
        {
            part = part.ToLower();
            locale = locale.ToLower();
            key = key.ToLower();

            var localization = ProviderGroupFactory.CreateProviderGroup(providerConfigName);

            var qualifier = new Qualifier.Unique(Part.Parse(part), new Locale(locale), key);
            var sanitizationResult =
                Sanitizer.Sanitize(content, SanitizationExclusionType.Cms, SanitizerOperatingMode.Input);

            if (sanitizationResult.ExternalizedErrors.Count > 0){
                return Json(new { ok = false,  sanitizationResult });
            } else { 
                var value = content;
                var qualifiedValue = new QualifiedValue(qualifier, value);

                localization.ValueManager.UpdateCreateValue(qualifiedValue);
                localization.HistoryManager.ProgressHistory(qualifiedValue, Session.Get<String>("author"));

                localization.ValueManager.Persist();
                if (localization.ValueManager != localization.HistoryManager)
                    localization.HistoryManager.Persist();

                return Json(new {ok = true});
            }
        }

        [ValidateInput(false)]
        public JsonResult MoveAndUpdateValue(String oldPart, String oldLocale, String oldKey, String newPart, String newLocale, String newKey, String newContent, String providerConfigName)
        {
            var sanitizationResult =
                Sanitizer.Sanitize(newContent, SanitizationExclusionType.Cms, SanitizerOperatingMode.Input);

            if (sanitizationResult.ExternalizedErrors.Count > 0)
            {
                return Json(new {ok = false, sanitizationResult});
            }
            else
            {
                oldPart = oldPart.ToLower();
                oldLocale = oldLocale.ToLower();
                oldKey = oldKey.ToLower();

                newPart = newPart.ToLower();
                newLocale = newLocale.ToLower();
                newKey = newKey.ToLower();

                var localization = ProviderGroupFactory.CreateProviderGroup(providerConfigName);

                // delete old Qualifier
                var oldQualifier = new Qualifier.Unique(Part.Parse(oldPart), new Locale(oldLocale), oldKey);
                var oldQualifiedValue = new QualifiedValue(oldQualifier, null);

                localization.ValueManager.DeleteValue(oldQualifier);
                localization.HistoryManager.ProgressHistory(oldQualifiedValue, Session.Get<String>("author"));

                // insert new Qualifier
                var newQualifier = new Qualifier.Unique(Part.Parse(newPart), new Locale(newLocale), newKey);
                var newQualifiedValue = new QualifiedValue(newQualifier, newContent);

                localization.ValueManager.UpdateCreateValue(newQualifiedValue);
                localization.HistoryManager.ProgressHistory(newQualifiedValue, Session.Get<String>("author"));

                localization.ValueManager.Persist();
                if (localization.ValueManager != localization.HistoryManager)
                {
                    localization.HistoryManager.Persist();
                }

                return Json(new {ok = true});
            }
        }

        [ValidateInput(false)]
        public JsonResult DeleteValue(String part, String locale, String key, String providerConfigName)
        {
            
            var localization = ProviderGroupFactory.CreateProviderGroup(providerConfigName);

            var qualifier = new Qualifier.Unique(Part.Parse(part), new Locale(locale), key);
            localization.ValueManager.DeleteValue(qualifier);
            localization.HistoryManager.ProgressHistory(new QualifiedValue(qualifier, null), Session.Get<String>("author"));

            localization.ValueManager.Persist();
            if (localization.ValueManager != localization.HistoryManager)
                localization.HistoryManager.Persist();

            return Json(new { ok = true });
        }

        private static void FixTree(IDictionary<Part, LocalizedPart> groupedParts, Part key)
        {
            var newKey = key.Parent;
            if (newKey == null || groupedParts.ContainsKey(newKey)) return;

            groupedParts.Add(newKey, new LocalizedPart(newKey, new List<QualifiedLocalization>(0)));
            FixTree(groupedParts, newKey);
        }
    }
}

BLocal.Web.Manager.MVC3/Views/DirectEditing/Index.cshtml
@using BLocal.Web.Manager.Models.DirectEditing
@model IndexModel
@{
    ViewBag.Title = "Manual Editing";
    ViewBag.PageName = "DirectEditing.Index";
}
@section Head {
    <script type="text/javascript">
        window.urls = window.urls || {};
        window.urls.current = '@Html.Raw(Url.Action("Index", "DirectEditing", new { providerConfigName = Model.Provider.Name }))';
        window.urls.updateCreateValue = '@Html.Raw(Url.Action("UpdateCreateValue", "DirectEditing", new { providerConfigName = Model.Provider.Name }))';
        window.urls.moveAndUpdateValue = '@Html.Raw(Url.Action("MoveAndUpdateValue", "DirectEditing", new { providerConfigName = Model.Provider.Name }))';
        window.urls.deleteValue = '@Html.Raw(Url.Action("DeleteValue", "DirectEditing", new { providerConfigName = Model.Provider.Name }))';
    </script>
}

<h1>@Html.ActionLink("Home", "Overview", "Home") - Manual Editing of <span style="color: @Model.Provider.Color">@Model.Provider.Name</span></h1>
<p><span class="open">open</span> | <span class="collapse">collapse</span> | <span class="reload">reload</span> | <span class="hardreload" title="dump localization cache, reload from scratch">hard reload</span></p>
    
<section class="general">
    <h2>Filter</h2>
    <form id="filterform">
        <div>
            <label>Part</label>
            @{ var nextLevelLocalizedParts = Model.Parts.ToList(); }
            @for (var level = 0; level < 5; level++) {
                var currentLevelLocalizedParts = nextLevelLocalizedParts.ToList();
                if (!currentLevelLocalizedParts.Any()) {
                    break;
                }
                nextLevelLocalizedParts = currentLevelLocalizedParts.SelectMany(part => part.Subparts).ToList();
                
                <select class="part" data-level="@level">
                    <option></option>
                    @foreach (var partName in currentLevelLocalizedParts.Select(part => part.Part.Name).Distinct()) {
                        <option>@partName</option>
                    }
                </select>
            }
        </div>
        <div><label for="key">Key</label> <input type="text" class="filter" id="key" /></div>
        <div><label for="locale">Locale</label> <input type="text" class="filter" id="locale" /></div>
        <div><label for="content">Content</label> <input type="text" class="filter" id="content" /></div>
        <div><input type="submit" value="Apply Filter" /></div>
    </form>
    <div><p class="result"></p></div>
</section>


@foreach(var localizedPart in Model.Parts) {
    @RenderPart(localizedPart)
}

@helper RenderPart(LocalizedPart part) {
    <section class="part" data-part="@part.Part.ToString()">
        <h2><span class="title">@part.Part.ToString()</span> [<span class="count">@part.Localizations.Count</span>]</h2>
        <section class="values">
            @foreach (var value in part.Localizations.OrderBy(value => value.Qualifier.Key).ThenBy(value => value.Qualifier.Locale.Name)) {
                <p class="value" data-locale="@value.Qualifier.Locale" data-key="@value.Qualifier.Key" title="Last edit by @value.History.LatestEntry().Author on @value.History.LatestEntry().DateTimeUtc.ToLocalTime()">
                    <span class="key">@value.Qualifier.Key</span>
                    <span class="locale"><nobr>@value.Qualifier.Locale</nobr></span>
                    <span class="content">@value.Value</span>
                    <span class="clear"></span>
                </p>
            }
        </section>
        @foreach(var subpart in part.Subparts) {
            @RenderPart(subpart)
        }
    </section>
}
    
<div id="details" class="popup">
    <h2>Details</h2>
    <form>
        <p><span class="lbl part">Part</span><span class="lbl key">Key</span><span class="lbl locale">Locale</span></p>
        <p><input type="text" class="val part"></input><input type="text" class="val key"></input><input type="text" class="val locale"></input></p>
        <p><span class="lbl">Content</span></p>
        <div><textarea class="content"></textarea></div>
        <div>
            <input type="button" class="save" value="Save"/>
            <input type="button" class="updaterecreate" style="display: none" value="Move" title="deletes current value, recreates to new value" />
            <input type="button" class="updatecopy" style="display: none" value="Copy" title="creates a copy if key or part changed, does not delete original" />
            <input class="updatedelete" type="button" value="Remove" title="bye-bye" />
            <p>(visible changes are indications, press reload to confirm)</p>
            <p id="manualEditErrors"></p>
        </div>
    </form>
</div>